// ABCDEF
const textpuul =  [
    {      // デバックテキスト ID タイトル番号 タイトル 問題文==========
        mondaibangou:0,
        mondaiban: "0:",
        taitoruna:"テストメッセージです",
        monndaina: "問題テストテキストです",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 1,
        textboxID: "textboxIDa",
        colsID: "4",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "テスト0です",
        botan1: "テスト1です",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanIDa0",
        botanID1:"botanIDa1",
        botanID2:"botanIDa2",
        botanID3:"botanIDa3",
        botanID4:"botanIDa4",
        botanup: [0,1,2,3,4],
        botanhp: [1,2,3,4,5],
        botantp: [2,3,4,5,6],
        // 次へ_no_off 
        next_no_off: 1,
        next:"次へ",
        nextID:"nextIDa",
    },{    // ID 　ID タイトル番号 タイトル 問題文==========
        mondaibanngou:1,
        mondaiban: "1",
        taitoruna:"IDを入れてください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 1,
        textboxID: "textboxIDb",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 0,
        botan_on_off1: 0,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "テスト0です",
        botan1: "テスト1です",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanIDb0",
        botanID1:"botanIDb1",
        botanID2:"botanIDb2",
        botanID3:"botanIDb3",
        botanID4:"botanIDb4",
        botanup: [0,1,2,3,4],
        botanhp: [1,2,3,4,5],
        botantp: [2,3,4,5,6],
        colsID: "7",
        // 次へ_no_off 
        next_no_off: 1,
        next:"次へ",
        nextID:"nextIDb",
    },{    // 体温 ID タイトル番号 タイトル 問題文==========
        mondaibanngou:2,
        mondaiban: "2",
        taitoruna:"体温を入れてください",
        monndaina: "36.0度の場合は360と記入してください",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 1,
        textboxID: "textboxIDc",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 0,
        botan_on_off1: 0,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "テスト0です",
        botan1: "テスト1です",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanIDc0",
        botanID1:"botanIDc1",
        botanID2:"botanIDc2",
        botanID3:"botanIDc3",
        botanID4:"botanIDc4",
        botanup: [0,1,2,3,4],
        botanhp: [1,2,3,4,5],
        botantp: [2,3,4,5,6],
        colsID: "3",
        // 次へ_no_off 
        next_no_off: 1,
        next:"次へ",
        nextID:"nextIDc",
    },{    // 脈拍 ID タイトル番号 タイトル 問題文==========
        mondaibanngou:3,
        mondaiban: "3",
        taitoruna:"脈拍を入れてください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 1,
        textboxID: "textboxIDd",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 0,
        botan_on_off1: 0,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "テスト0です",
        botan1: "テスト1です",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanIDd0",
        botanID1:"botanIDd1",
        botanID2:"botanIDd2",
        botanID3:"botanIDd3",
        botanID4:"botanIDd4",
        botanup: [0,1,2,3,4],
        botanhp: [1,2,3,4,5],
        botantp: [2,3,4,5,6],
        colsID: "3",
        // 次へ_no_off 
        next_no_off: 1,
        next:"次へ",
        nextID:"nextIDd",
    },{    // 睡眠 ID タイトル番号 タイトル 問題文==========
        mondaibanngou:4,
        mondaiban: "4",
        taitoruna:"睡眠時間を入れてください",
        monndaina: "時間のみを入れてください",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 1,
        textboxID: "textboxIDe",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 0,
        botan_on_off1: 0,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "テスト0です",
        botan1: "テスト1です",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanIDe0",
        botanID1:"botanIDe1",
        botanID2:"botanIDe2",
        botanID3:"botanIDe3",
        botanID4:"botanIDe4",
        botanup: [0,1,2,3,4],
        botanhp: [1,2,3,4,5],
        botantp: [2,3,4,5,6],
        colsID: "2",
        // 次へ_no_off 
        next_no_off: 1,
        next:"次へ",
        nextID:"nextIDe",
    },{    // ご飯 ID タイトル番号 タイトル 問題文==========
        mondaibanngou:5,
        mondaiban: "5",
        taitoruna:"朝食について教えてください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDf",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　 食べてない 　",
        botan1: "　 飲み物だけ 　",
        botan2: "　　軽食のみ　　",
        botan3: "しっかりと食べた",
        botan4: "テスト4です",
        botanID0:"botanIDf0",
        botanID1:"botanIDf1",
        botanID2:"botanIDf2",
        botanID3:"botanIDf3",
        botanID4:"botanIDf4",
        botanup: [1,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [1,1,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDg",
    }
]

const kekkatext = [
    "万全の状態です",
    "問題はありませんが少し注意してください",
    "少し問題が起こりやすい状態です。注意してください",
    "問題が起こりやすい状態です。十分注意してください",
    "あまり推奨しません。行う際には十分注意して行ってください",
    "仕事を推奨しません。失敗が起こりやすいです。一人での業務は推奨しません",
    "非常危険です。失敗が起こりやすい状態なため、業務を行わないことを推奨します",
    "大変、非常に危ない状態です。問題の発生する前に対処が推奨されます",
]
const newtext = [
    "新しい仕事に向いています",
    "新しい仕事に向いています。少し注意して仕事に取り組んでください",
    "少し新しい仕事に向いています。注意して仕事に取り組んでください",
    "あまり新しい仕事に向いていません。行う際には注意して取り組んでください",
    "新しい仕事に向いていません。行う仕事は2人以上で確認してください",
    "新しい仕事に向いていません。事故や問題が起こりやすい状態です",
    "少し新しい仕事に向いています",
    "問題が起こりやすい状態です。十分注意してください",
    "新しい仕事に向いていません",
    "非常に注意してください。新しい仕事に向いていません。事故を起こしやすい状態です",
    "あまり新しい仕事に向いていません",
    "新しい仕事に向いていません。行う際には注意して取り組んでください",
    "非常に注意してください。事故を起こす可能性があります。仕事を行うことを推奨しません",
]

const oidtext = [
    "万全の状態です",
    "問題はありませんが、注意してください",
    "少し問題があります、注意してください",
    "少し問題があります。十分注意してください",
    "問題が起こりやすい状況です。十分に注意してください",
    "大変問題の問題の起こりやすい状態です",
    "現在仕事に向いていない状況です",
]

const othretext = [
    "確認ミスが発生しやすいです",
    "計算を間違えやすい状態です"	,
    "仕事のダブルチェックを推奨します",
    "ダブルチェックが必要です",
    "複雑な計算を間違える可能性があります",
    "調子がいい状態です",
    "計算を間違えやすい状態です",
    "仕事のダブルチェックを推奨します",
    "二人以上での業務を推奨します",
    "間違った思考をする可能性があります",
    "イライラする可能性があります",
    "強い眠気を感じる危険性があります",
    "複雑な作業において認識の齟齬が生まれやすいです",
    "注意が散漫しやすい状態です",
    "頭が回らない可能性があります",
    "問題が起こりやすい状態です",
    "正しい判断ができない可能性があります",
    "鬱かもしれません",
    "言語への理解に問題が発生しやすい可能性があります",
    "事故にが起こりやすい状態です",
    "正しい思考ができていない可能性があります",
    "問題行動を起こす危険性があります",
]