const hp2puul =  [
    {      // G ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H0",
        mondaiban: "2H0",
        taitoruna:"計算してください",
        monndaina: "3-2(5-7)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　　-2　　",
        botan1: "　　7　　",
        botan2: "　　2　　",
        botan3: "　　9　　",
        botan4: "　　-4　　",
        botanID0:"botanID02h0",
        botanID1:"botanID12h0",
        botanID2:"botanID22h0",
        botanID3:"botanID32h0",
        botanID4:"botanID42h0",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
    },{    // H ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H1",
        mondaiban: "2H1",
        taitoruna:"計算をしてください",
        monndaina: "8+2(4-6)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　　2　　",
        botan1: "　　8　　",
        botan2: "　　-6　　",
        botan3: "　　-10　　",
        botan4: "　　4　　",
        botanID0:"botanID02h1",
        botanID1:"botanID12h1",
        botanID2:"botanID22h1",
        botanID3:"botanID32h1",
        botanID4:"botanID42h1",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,1,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",     
    },{    // I ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H2",
        mondaiban: "2H2",
        taitoruna:"計算してください",
        monndaina: "2(6-8)+6",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　　2　　",
        botan1: "　　-2　　",
        botan2: "　　0　　",
        botan3: "　　4　　",
        botan4: "　　-4　　",
        botanID0:"botanID02h2",
        botanID1:"botanID12h2",
        botanID2:"botanID22h2",
        botanID3:"botanID32h2",
        botanID4:"botanID42h2",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // J ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H3",
        mondaiban: "2H3",
        taitoruna:"計算してください",
        monndaina: "4+5(2+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　26　　",
        botan1: "　　45　　",
        botan2: "　　24　　",
        botan3: "　　36　　",
        botan4: "テスト4です",
        botanID0:"botanID02h3",
        botanID1:"botanID12h3",
        botanID2:"botanID22h3",
        botanID3:"botanID32h3",
        botanID4:"botanID42h3",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // K ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H4",
        mondaiban: "2H4",
        taitoruna:"計算してください",
        monndaina: "2+4(1+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　16　　",
        botan1: "　　24　　",
        botan2: "　　15　　",
        botan3: "　　18　　",
        botan4: "テスト4です",
        botanID0:"botanID02h4",
        botanID1:"botanID12h4",
        botanID2:"botanID22h4",
        botanID3:"botanID32h4",
        botanID4:"botanID42h4",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
    },{    // L ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H5",
        mondaiban: "2H5",
        taitoruna:"計算してください",
        monndaina: "4+4(1+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　22　　",
        botan1: "　　24　　",
        botan2: "　　16　　",
        botan3: "　　14　　",
        botan4: "テスト4です",
        botanID0:"botanID02h5",
        botanID1:"botanID12h5",
        botanID2:"botanID22h5",
        botanID3:"botanID32h5",
        botanID4:"botanID42h5",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
        
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H6",
        mondaiban: "2H6",
        taitoruna:"計算してください",
        monndaina: "-2+4(1+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　7　　",
        botan1: "　　25　　",
        botan2: "　　14　　",
        botan3: "　　12　　",
        botan4: "テスト4です",
        botanID0:"botanID02h6",
        botanID1:"botanID12h6",
        botanID2:"botanID22h6",
        botanID3:"botanID32h6",
        botanID4:"botanID42h6",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // N ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H7",
        mondaiban: "2H7",
        taitoruna:"計算してください",
        monndaina: "-3+2(1+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　5　　",
        botan1: "　　-4　　",
        botan2: "　　8　　",
        botan3: "　　-2　　",
        botan4: "テスト4です",
        botanID0:"botanID02h7",
        botanID1:"botanID12h7",
        botanID2:"botanID22h7",
        botanID3:"botanID32h7",
        botanID4:"botanID42h7",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // O ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H8",
        mondaiban: "2H8",
        taitoruna:"計算してください",
        monndaina: "-5+3(1+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　-4　　",
        botan1: "　　-6　　",
        botan2: "　　6　　",
        botan3: "　　4　　",
        botan4: "テスト4です",
        botanID0:"botanID02h8",
        botanID1:"botanID12h8",
        botanID2:"botanID22h8",
        botanID3:"botanID32h8",
        botanID4:"botanID42h8",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{
        mondaibanngou: "2H9",
        mondaiban: "2H9",
        taitoruna:"計算してください",
        monndaina: "-4+2(1+1)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　0　　",
        botan1: "　　-4　　",
        botan2: "　　6　　",
        botan3: "　　3　　",
        botan4: "テスト4です",
        botanID0:"botanID02h9",
        botanID1:"botanID12h9",
        botanID2:"botanID22h9",
        botanID3:"botanID32h9",
        botanID4:"botanID42h9",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
    },{
        mondaibanngou: "2H10",
        mondaiban: "2H10",
        taitoruna:"計算してください",
        monndaina: "-4+5(3+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　21　　",
        botan1: "　　26　　",
        botan2: "　　6　　",
        botan3: "　　4　　",
        botan4: "テスト4です",
        botanID0:"botanID02h10",
        botanID1:"botanID12h10",
        botanID2:"botanID22h10",
        botanID3:"botanID32h10",
        botanID4:"botanID42h10",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H11",
        mondaiban: "2H11",
        taitoruna:"計算してください",
        monndaina: "2-3(2+1)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　7　　",
        botan1: "　　3　　",
        botan2: "　　-7　　",
        botan3: "　　-3　　",
        botan4: "テスト4です",
        botanID0:"botanID02h11",
        botanID1:"botanID12h11",
        botanID2:"botanID22h11",
        botanID3:"botanID32h11",
        botanID4:"botanID42h11",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // N ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H12",
        mondaiban: "2H12",
        taitoruna:"計算してください",
        monndaina: "2-5(3+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　6　　",
        botan1: "　　-18　　",
        botan2: "　　20　　",
        botan3: "　　-28　　",
        botan4: "テスト4です",
        botanID0:"botanID02h12",
        botanID1:"botanID12h12",
        botanID2:"botanID22h12",
        botanID3:"botanID32h12",
        botanID4:"botanID42h12",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
        
    },{    // O ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H13",
        mondaiban: "2H13",
        taitoruna:"計算してください",
        monndaina: "1-(3+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　 -5　　",
        botan1: "　　4　　",
        botan2: "　　8　　",
        botan3: "　　0　　",
        botan4: "テスト4です",
        botanID0:"botanID02h13",
        botanID1:"botanID12h13",
        botanID2:"botanID22h13",
        botanID3:"botanID32h13",
        botanID4:"botanID42h13",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{
        mondaibanngou: "2H14",
        mondaiban: "2H14",
        taitoruna:"計算してください",
        monndaina: "1-(3+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　8　　",
        botan1: "　　-5　　",
        botan2: "　　0　　",
        botan3: "　　7　　",
        botan4: "テスト4です",
        botanID0:"botanID02h14",
        botanID1:"botanID12h14",
        botanID2:"botanID22h14",
        botanID3:"botanID32h14",
        botanID4:"botanID42h14",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{
        mondaibanngou: "2H15",
        mondaiban: "2H15",
        taitoruna:"計算してください",
        monndaina: "-1+2(-1+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　-2　　",
        botan1: "　　-1　　",
        botan2: "　　2　　",
        botan3: "　　1　　",
        botan4: "テスト4です",
        botanID0:"botanID02h15",
        botanID1:"botanID12h15",
        botanID2:"botanID22h15",
        botanID3:"botanID32h15",
        botanID4:"botanID42h15",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // O ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H16",
        mondaiban: "2H16",
        taitoruna:"計算してください",
        monndaina: "-5+(-1+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　6　　",
        botan1: "　　-4　　",
        botan2: "　　4　　",
        botan3: "　　-6　　",
        botan4: "テスト4です",
        botanID0:"botanID02h16",
        botanID1:"botanID12h16",
        botanID2:"botanID22h16",
        botanID3:"botanID32h16",
        botanID4:"botanID42h16",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",           
    },{
        mondaibanngou: "2H17",
        mondaiban: "2H17",
        taitoruna:"計算してください",
        monndaina: "-3+2(-3+3)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　3　　",
        botan1: "　　0　　",
        botan2: "　　-3　　",
        botan3: "　　5　　",
        botan4: "テスト4です",
        botanID0:"botanID02h17",
        botanID1:"botanID12h17",
        botanID2:"botanID22h17",
        botanID3:"botanID32h17",
        botanID4:"botanID42h17",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{
        mondaibanngou: "2H18",
        mondaiban: "2H18",
        taitoruna:"計算してください",
        monndaina: "-5+3(-2+1)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　7　　",
        botan1: "　　2　　",
        botan2: "　　8　　",
        botan3: "　　-8　　",
        botan4: "テスト4です",
        botanID0:"botanID02h18",
        botanID1:"botanID12h18",
        botanID2:"botanID22h18",
        botanID3:"botanID32h18",
        botanID4:"botanID42h18",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H19",
        mondaiban: "2H19",
        taitoruna:"計算してください",
        monndaina: "-2+(-3+2)",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　1　　",
        botan1: "　　-1　　",
        botan2: "　　3　　",
        botan3: "　　-3　　",
        botan4: "テスト4です",
        botanID0:"botanID02h19",
        botanID1:"botanID12h19",
        botanID2:"botanID22h19",
        botanID3:"botanID32h19",
        botanID4:"botanID42h19",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // N ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H20",
        mondaiban: "2H20",
        taitoruna:"答えが12になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "2(2+4)",
        botan1: "5(3+1)",
        botan2: "5(2+1)",
        botan3: "4(2+2)",
        botan4: "テスト4です",
        botanID0:"botanID02h20",
        botanID1:"botanID12h20",
        botanID2:"botanID22h20",
        botanID3:"botanID32h20",
        botanID4:"botanID42h20",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
        
    },{    // O ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H21",
        mondaiban: "2H21",
        taitoruna:"答えが-16になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "7(5+8)",
        botan1: "2(3+1)",
        botan2: "5(2-1)",
        botan3: "-4(2+2)",
        botan4: "テスト4です",
        botanID0:"botanID02h21",
        botanID1:"botanID12h21",
        botanID2:"botanID22h21",
        botanID3:"botanID32h21",
        botanID4:"botanID42h21",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",          
    },{
        mondaibanngou: "2H22",
        mondaiban: "2H22",
        taitoruna:"答えがを-4になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "-(1+2)",
        botan1: "-(1+3)",
        botan2: "4(3+1)",
        botan3: "5(2+3)",
        botan4: "テスト4です",
        botanID0:"botanID02h22",
        botanID1:"botanID12h22",
        botanID2:"botanID22h22",
        botanID3:"botanID32h22",
        botanID4:"botanID42h22",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{
        mondaibanngou: "2H23",
        mondaiban: "2H23",
        taitoruna:"答えがを-10になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "5(-3+1)",
        botan1: "4(2-1)",
        botan2: "2(2-1)",
        botan3: "4(3-1)",
        botan4: "テスト4です",
        botanID0:"botanID02h23",
        botanID1:"botanID12h23",
        botanID2:"botanID22h23",
        botanID3:"botanID32h23",
        botanID4:"botanID42h23",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // I ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H24",
        mondaiban: "2H24",
        taitoruna:"答えがを14になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "3(2+1)",
        botan1: "2(2+4)",
        botan2: "2(3+4)",
        botan3: "6(1+1)",
        botan4: "テスト4です",
        botanID0:"botanID02h24",
        botanID1:"botanID12h24",
        botanID2:"botanID22h24",
        botanID3:"botanID32h24",
        botanID4:"botanID42h24",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",            
    },{    // J ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H25",
        mondaiban: "2H25",
        taitoruna:"答えがを-9になる式を選んでください",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "-5(2+5)",
        botan1: "-5(1+2)",
        botan2: "-2(3+5)",
        botan3: "-3(2+1)",
        botan4: "テスト4です",
        botanID0:"botanID02h25",
        botanID1:"botanID12h25",
        botanID2:"botanID22h25",
        botanID3:"botanID32h25",
        botanID4:"botanID42h25",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",               
    },{    // K ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H26",
        mondaiban: "2H26",
        taitoruna:"●の中に入る数字を選んでください",
        monndaina: "-4(●+3)＝-20",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　2　　",
        botan1: "　　3　　",
        botan2: "　　-7　　",
        botan3: "　　-2　　",
        botan4: "テスト4です",
        botanID0:"botanID02h26",
        botanID1:"botanID12h26",
        botanID2:"botanID22h26",
        botanID3:"botanID32h26",
        botanID4:"botanID42h26",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // L ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H27",
        mondaiban: "2H27",
        taitoruna:"●の中に入る数字を選んでください",
        monndaina: "-5(●+2)=-15",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　-1　　",
        botan1: "　　1　　",
        botan2: "　　5　　",
        botan3: "　　7　　",
        botan4: "テスト4です",
        botanID0:"botanID02h27",
        botanID1:"botanID12h27",
        botanID2:"botanID22h27",
        botanID3:"botanID32h27",
        botanID4:"botanID42h27",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",        
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H28",
        mondaiban: "2H28",
        taitoruna:"●の中に入る数字を選んでください",
        monndaina: "5(-●+5)=20",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　-1　　",
        botan1: "　　2　　",
        botan2: "　　1　　",
        botan3: "　　3　　",
        botan4: "テスト4です",
        botanID0:"botanID02h28",
        botanID1:"botanID12h28",
        botanID2:"botanID22h28",
        botanID3:"botanID32h28",
        botanID4:"botanID42h28",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",            
    },{    // N ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H29",
        mondaiban: "2H29",
        taitoruna:"●の中に入る数字を選んでください",
        monndaina: "4(-1+●)=4",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　4　　",
        botan1: "　　-2　　",
        botan2: "　　6　　",
        botan3: "　　2　　",
        botan4: "テスト4です",
        botanID0:"botanID02h29",
        botanID1:"botanID12h29",
        botanID2:"botanID22h29",
        botanID3:"botanID32h29",
        botanID4:"botanID42h29",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",               
    },{    // O ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "2H30",
        mondaiban: "2H30",
        taitoruna:"●の中に入る数字を選んでください",
        monndaina: "5(1-●)=-10",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh1",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　3　　",
        botan1: "　　8　　",
        botan2: "　　6　　",
        botan3: "　　2　　",
        botan4: "テスト4です",
        botanID0:"botanID02h30",
        botanID1:"botanID12h30",
        botanID2:"botanID22h30",
        botanID3:"botanID32h30",
        botanID4:"botanID42h30",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,1,1,1],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh1",
             
    }
]