const hppuul =  [
    {      // デバックテキスト ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H0",
        mondaiban: "H0",
        taitoruna:"女性の司書と司書どちらが多いか",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　 司書 　",
        botan1: "女性の司書",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h0",
        botanID1:"botanID1h0",
        botanID2:"botanID2h0",
        botanID3:"botanID3h0",
        botanID4:"botanID4h0",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // ID 　ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H1",
        mondaiban: "H1",
        taitoruna:"どちらの可能性が高いだろうか",
        monndaina: "リンダは31歳、独身で、率直に意見を言い、非常に聡明である。大学では哲学を専攻した。学生時代、彼女は、人種差別や社会正義の問題に強く関心をもち、反核デモに参加していた。次の2つのうち、どちらの可能性が高いだろうか。",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "リンダは、銀行員である",
        botan1: "リンダは、銀行員であり、女性解放運動もしている",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h1",
        botanID1:"botanID1h1",
        botanID2:"botanID2h1",
        botanID3:"botanID3h1",
        botanID4:"botanID4h1",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",
        
    },{    // 体温 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H2",
        mondaiban: "H2",
        taitoruna:"どちらの方が高いだろうか",
        monndaina: "A:30%の確率で10000円もらうか　B:30％の確率で3000円を3回もらえるか",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　 A　",
        botan1: "　 B 　",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h2",
        botanID1:"botanID1h2",
        botanID2:"botanID2h2",
        botanID3:"botanID3h2",
        botanID4:"botanID4h2",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // 脈拍 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H3",
        mondaiban: "H3",
        taitoruna:"どちらの確率が高いか",
        monndaina: "A:非常に頭の良い女性は、自分より頭の悪い男性と結婚する確率が高い　B:非常に頭の良い女性は、自分と同じくらい頭の良い男性と結婚する確率が高い",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　A　　",
        botan1: "　　B　　",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h3",
        botanID1:"botanID1h3",
        botanID2:"botanID2h3",
        botanID3:"botanID3h3",
        botanID4:"botanID4h3",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // 睡眠 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H4",
        mondaiban: "H4",
        taitoruna:"どちらの確率が高いか",
        monndaina: "A：阪神の4番が2回ホームランを打った後、次の打席でホームランを打つ確立　　B：阪神の4番が2回ホームランを打った後、次の打席でアウトになる確立",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　A　　",
        botan1: "　　B　　",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h4",
        botanID1:"botanID1h4",
        botanID2:"botanID2h4",
        botanID3:"botanID3h4",
        botanID4:"botanID4h4",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",               
    },{    // ご飯 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H5",
        mondaiban: "H5",
        taitoruna:"上司の行動は正しいのか",
        monndaina: "山田は、最近調子が悪く仕事のミスも多かった、そのため、上司が叱ったところ次の日から山田のミスが減った。",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　正しい　　",
        botan1: "　正しくない　",
        botan2: "どちらでもない",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h5",
        botanID1:"botanID1h5",
        botanID2:"botanID2h5",
        botanID3:"botanID3h5",
        botanID4:"botanID4h5",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{
        mondaibanngou: "H6",
        mondaiban: "H6",
        taitoruna:"上司の行動は正しいのか",
        monndaina: "山田が体調を崩していたので上司が、山田に休みを与えた。山田は次の日体調が戻った",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　正しい　　",
        botan1: "　正しくない　",
        botan2: "どちらでもない",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h6",
        botanID1:"botanID1h6",
        botanID2:"botanID2h6",
        botanID3:"botanID3h6",
        botanID4:"botanID4h6",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{
        mondaibanngou: "H7",
        mondaiban: "H7",
        taitoruna:"上司の行動は正しいのか",
        monndaina: "山田が体調を崩していたので上司が、山田にBドリンクを与えた。山田は次の日体調が戻った",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　正しい　　",
        botan1: "　正しくない　",
        botan2: "どちらでもない",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h7",
        botanID1:"botanID1h7",
        botanID2:"botanID2h7",
        botanID3:"botanID3h7",
        botanID4:"botanID4h7",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{
        mondaibanngou: "H8",
        mondaiban: "H8",
        taitoruna:"次のボクシングの試合で確率の高い結果を予測してください",
        monndaina: "令和の怪物といわれたボクサー上司VS無断欠勤の鬼　山田",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "上司の勝利",
        botan1: "上司が第1セットでKO勝利",
        botan2: "上司が第1セットを落とすが勝利",
        botan3: "山田が3セットを取り勝利",
        botan4: "テスト4です",
        botanID0:"botanID0h8",
        botanID1:"botanID1h8",
        botanID2:"botanID2h8",
        botanID3:"botanID3h8",
        botanID4:"botanID4h8",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{
        mondaibanngou: "H9",
        mondaiban: "H9",
        taitoruna:"どちらの方が確立が高いか",
        monndaina: "　上司は、タクシーにひき逃げにあった。その時近くにいた山田は、その地域で10％のタクシーを管理する緑タクシーであったと述べている。その後の実況見分調査で山田は、緑タクシーと、その地域の90%のタクシーを管理する青タクシーとの区別を80%の確率で判別できることがわかった。上司をひき逃げしたタクシーは、緑タクシーか青タクシーかどちらの確率が高いか",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 0,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "　　緑タクシー　　",
        botan1: "　　青タクシー　　",
        botan2: "テスト2です",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h9",
        botanID1:"botanID1h9",
        botanID2:"botanID2h9",
        botanID3:"botanID3h9",
        botanID4:"botanID4h9",
        botanup: [0,0,0,0,0],
        botanhp: [0,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",
    },{    // ID 　ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H11",
        mondaiban: "H11",
        taitoruna:"コインを5回投げた結果、確率として高いものをあげよ",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "表-裏-裏-表-表",
        botan1: "裏-裏-裏-裏-裏",
        botan2: "どれでもない",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h11",
        botanID1:"botanID1h11",
        botanID2:"botanID2h11",
        botanID3:"botanID3h11",
        botanID4:"botanID4h11",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // 体温 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H12",
        mondaiban: "H12",
        taitoruna:"サイコロを3回振った結果、確率として高いものを選べ",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "6-6-6",
        botan1: "2-4-3",
        botan2: "3-6-1",
        botan3: "どれでもない",
        botan4: "テスト4です",
        botanID0:"botanID0h12",
        botanID1:"botanID1h12",
        botanID2:"botanID2h12",
        botanID3:"botanID3h12",
        botanID4:"botanID4h12",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,1,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // 脈拍 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H13",
        mondaiban: "H13",
        taitoruna:"コインを4回投げた結果、確率として高いものをあげよ",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 0,
        botan_on_off4: 0,
        botan0: "表-表-表-表",
        botan1: "表-裏-裏-表",
        botan2: "どれでもない",
        botan3: "テスト3です",
        botan4: "テスト4です",
        botanID0:"botanID0h13",
        botanID1:"botanID1h13",
        botanID2:"botanID2h13",
        botanID3:"botanID3h13",
        botanID4:"botanID4h13",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",        
    },{    // 睡眠 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H14",
        mondaiban: "H14",
        taitoruna:"アメリカの一年間の金額を入れてください",
        monndaina: "例：日本人のウクライナに寄付する金額の平均は8千円以上です。",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "　　1万円　　",
        botan1: "　　5万円　　",
        botan2: "　　5千円　　",
        botan3: "　　1千円　　",
        botan4: "テスト4です",
        botanID0:"botanID0h14",
        botanID1:"botanID1h14",
        botanID2:"botanID2h14",
        botanID3:"botanID3h14",
        botanID4:"botanID4h14",
        botanup: [0,0,0,0,0],
        botanhp: [1,1,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",
    },{    // ご飯 ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "H15",
        mondaiban: "H15",
        taitoruna:"インドのGDPとして正しいものはどれですか？",
        monndaina: "例：アメリカは約2000万ドルです",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 0,
        botan0: "約500万ドル",
        botan1: "約100万ドル",
        botan2: "約1000万ドル",
        botan3: "約300万ドル",
        botan4: "テスト4です",
        botanID0:"botanID0h15",
        botanID1:"botanID1h15",
        botanID2:"botanID2h15",
        botanID3:"botanID3h15",
        botanID4:"botanID4h15",
        botanup: [0,0,0,0,0],
        botanhp: [1,0,1,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDh",             
    }
]
    
        
    