const utpuul =  [
    {      // G ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT0",
        mondaiban: "UT0",
        taitoruna:"よく気持ちが落ち込んでいる",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT0",
        botanID1:"botanID1UT0",
        botanID2:"botanID2UT0",
        botanID3:"botanID3UT0",
        botanID4:"botanID4UT0",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // H ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT1",
        mondaiban: "UT1",
        taitoruna:"寝つきが悪くあまり眠れない",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT1",
        botanID1:"botanID1UT1",
        botanID2:"botanID2UT1",
        botanID3:"botanID3UT1",
        botanID4:"botanID4UT1",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // I ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT2",
        mondaiban: "UT2",
        taitoruna:"食欲がわかない",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT2",
        botanID1:"botanID1UT2",
        botanID2:"botanID2UT2",
        botanID3:"botanID3UT2",
        botanID4:"botanID4UT2",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",
        
    },{    // J ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT3",
        mondaiban: "UT3",
        taitoruna:"身体がだるく、疲れやすい",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT3",
        botanID1:"botanID1UT3",
        botanID2:"botanID2UT3",
        botanID3:"botanID3UT3",
        botanID4:"botanID4UT3",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",
        
    },{    // K ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT4",
        mondaiban: "UT4",
        taitoruna:"集中力が続かない",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT4",
        botanID1:"botanID1UT4",
        botanID2:"botanID2UT4",
        botanID3:"botanID3UT4",
        botanID4:"botanID4UT4",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // L ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT5",
        mondaiban: "UT5",
        taitoruna:"日頃していることに、満足感が持てない",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT5",
        botanID1:"botanID1UT5",
        botanID2:"botanID2UT5",
        botanID3:"botanID3UT5",
        botanID4:"botanID4UT5",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT6",
        mondaiban: "UT6",
        taitoruna:"これまでできていたことができない",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT6",
        botanID1:"botanID1UT6",
        botanID2:"botanID2UT6",
        botanID3:"botanID3UT6",
        botanID4:"botanID4UT6",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{      // G ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT7",
        mondaiban: "UT7",
        taitoruna:"物事を悲観的に考える",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT7",
        botanID1:"botanID1UT7",
        botanID2:"botanID2UT7",
        botanID3:"botanID3UT7",
        botanID4:"botanID4UT7",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // H ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT8",
        mondaiban: "UT8",
        taitoruna:"食欲がなくなってきた、あるいは過食するようになった",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT8",
        botanID1:"botanID1UT8",
        botanID2:"botanID2UT8",
        botanID3:"botanID3UT8",
        botanID4:"botanID4UT8",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // I ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT9",
        mondaiban: "UT9",
        taitoruna:"気持ちが落ち着かず、イライラしやすい",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT9",
        botanID1:"botanID1UT9",
        botanID2:"botanID2UT9",
        botanID3:"botanID3UT9",
        botanID4:"botanID4UT9",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // J ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT10",
        mondaiban: "UT10",
        taitoruna:"趣味への興味が薄くなってきた",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT10",
        botanID1:"botanID1UT10",
        botanID2:"botanID2UT10",
        botanID3:"botanID3UT10",
        botanID4:"botanID4UT10",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // K ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT11",
        mondaiban: "UT11",
        taitoruna:"うれしさを感じにくくなった",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT11",
        botanID1:"botanID1UT11",
        botanID2:"botanID2UT11",
        botanID3:"botanID3UT11",
        botanID4:"botanID4UT11",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // L ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT12",
        mondaiban: "UT12",
        taitoruna:"味覚の好みが変わった",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT12",
        botanID1:"botanID1UT12",
        botanID2:"botanID2UT12",
        botanID3:"botanID3UT12",
        botanID4:"botanID4UT12",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",        
    },{    // M ID タイトル番号 タイトル 問題文==========
        mondaibanngou: "UT13",
        mondaiban: "UT13",
        taitoruna:"漠然とした不安を感じる",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT13",
        botanID1:"botanID1UT13",
        botanID2:"botanID2UT13",
        botanID3:"botanID3UT13",
        botanID4:"botanID4UT13",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",
    },{
        mondaibanngou: "UT14",
        mondaiban: "UT14",
        taitoruna:"動悸、息切れが起こりやすい",
        monndaina: "",
        // テキストbox_on_oof テキストboxID
        textbox_on_off: 0,
        textboxID: "textboxIDh",
        // ボタン_on_off ボタン名前 ボタンID
        botan_on_off0: 1,
        botan_on_off1: 1,
        botan_on_off2: 1,
        botan_on_off3: 1,
        botan_on_off4: 1,
        botan0: "　よく当てはまる　",
        botan1: "　　当てはまる　　",
        botan2: "　どちらでもない　",
        botan3: "　当てはまらない　",
        botan4: "全く当てはまらない",
        botanID0:"botanID0UT14",
        botanID1:"botanID1UT14",
        botanID2:"botanID2UT14",
        botanID3:"botanID3UT14",
        botanID4:"botanID4UT14",
        botanup: [2,1,0,0,0],
        botanhp: [0,0,0,0,0],
        botantp: [0,0,0,0,0],
        // 次へ_no_off 
        next_no_off: 0,
        next:"次へ",
        nextID:"nextIDUT",
    }
]